import { useEffect, useMemo, useState, type FormEvent } from 'react'
import { listMyInstitutionRoster } from '../../api/institutions.api'
import { listIndustryOpportunities, publishUniversityOpportunity } from '../../api/industry.api'
import { addProjectMember, addProjectRecord, advanceProjectStage, getProjectBoard, listAuthorizedProjects, listMilestoneEvidence, listMilestoneReviews, listProjectMembers, listProjectProposals, submitMilestoneEvidence, submitProjectProposal } from '../../api/projects.api'
import { useAuth } from '../../features/auth/AuthContext'
import type { CollaborationType, IndustryOpportunity, InstitutionRosterMember, MilestoneEvidence, MilestoneReview, ProjectBoard as ProjectBoardData, ProjectMembership, ProjectMilestone, ProjectRecord, ProposalInput, ProposalRevision } from '../../api/types'
import type { Role } from '../../constants/roles'
import './ProjectBoard.css'
import './ProjectOutcome.css'

type RecordKind = 'deliverables' | 'ipDisclosures' | 'testRecords'
const recordLabels: Record<RecordKind, string> = { deliverables: 'Deliverables', ipDisclosures: 'IP disclosures', testRecords: 'Test records' }
const supportLabels: Record<CollaborationType, string> = { mentorship: 'Mentorship', funding: 'Funding', prototyping: 'Prototyping', deployment: 'Deployment', technology_transfer: 'Technology transfer' }
const formatDate = (value: string) => { const date = new Date(value); return Number.isNaN(date.getTime()) ? 'Date unavailable' : new Intl.DateTimeFormat('en-IN', { day: 'numeric', month: 'short', year: 'numeric' }).format(date) }
const projectFromHash = () => { const hash = window.location.hash.replace(/^#\/?/, ''); const [path, query] = hash.split('?'); const pathProject = path.startsWith('projects/') ? decodeURIComponent(path.slice('projects/'.length)) : ''; return pathProject || new URLSearchParams(query).get('project') || localStorage.getItem('civicx_project_id') || '' }

export default function ProjectBoard({ role }: { role: Role }) {
  const { user } = useAuth()
  const [projectId, setProjectId] = useState(projectFromHash)
  const [projects, setProjects] = useState<Array<{ id: string; title: string; summary: string; domain: string; department: string; currentStage: string; version: number; updatedAt: string }>>([])
  const [board, setBoard] = useState<ProjectBoardData | null>(null)
  const [members, setMembers] = useState<ProjectMembership[]>([])
  const [roster, setRoster] = useState<InstitutionRosterMember[]>([])
  const [proposals, setProposals] = useState<ProposalRevision[]>([])
  const [evidenceHistory, setEvidenceHistory] = useState<MilestoneEvidence[]>([])
  const [reviewHistory, setReviewHistory] = useState<MilestoneReview[]>([])
  const [opportunity, setOpportunity] = useState<IndustryOpportunity | null>(null)
  const [selectedMilestone, setSelectedMilestone] = useState<ProjectMilestone | null>(null)
  const [recordKind, setRecordKind] = useState<RecordKind>('deliverables')
  const [recordTitle, setRecordTitle] = useState('')
  const [recordDetail, setRecordDetail] = useState('')
  const [teamUserId, setTeamUserId] = useState('')
  const [teamRole, setTeamRole] = useState<'mentor' | 'student'>('student')
  const [proposal, setProposal] = useState<ProposalInput>({ approach: '', timeline: '', beneficiaries: '', rootCause: '', workPlan: '', risks: '', resources: '' })
  const [opportunityTitle, setOpportunityTitle] = useState('')
  const [opportunitySummary, setOpportunitySummary] = useState('')
  const [opportunityNeeds, setOpportunityNeeds] = useState<CollaborationType[]>([])
  const [evidenceNote, setEvidenceNote] = useState('')
  const [evidenceLinks, setEvidenceLinks] = useState('')
  const [notice, setNotice] = useState('')
  const [error, setError] = useState('')
  const [busy, setBusy] = useState(false)
  const [loading, setLoading] = useState(true)
  const [showTeam, setShowTeam] = useState(false)
  const [showProposal, setShowProposal] = useState(false)
  const [showOpportunity, setShowOpportunity] = useState(false)
  const [showEvidenceForm, setShowEvidenceForm] = useState(false)

  const load = async () => {
    setLoading(true); setError('')
    try {
      const summaries = await listAuthorizedProjects(); setProjects(summaries)
      if (!projectId) { setBoard(null); setMembers([]); setProposals([]); setEvidenceHistory([]); setReviewHistory([]); setOpportunity(null); return }
      const [nextBoard, nextMembers, nextProposals, nextEvidence, nextReviews, publishedOpportunities] = await Promise.all([getProjectBoard(projectId), listProjectMembers(projectId), listProjectProposals(projectId), listMilestoneEvidence(projectId), listMilestoneReviews(projectId), role === 'university' ? listIndustryOpportunities() : Promise.resolve([])])
      setBoard(nextBoard); setMembers(nextMembers); setProposals(nextProposals); setEvidenceHistory(nextEvidence); setReviewHistory(nextReviews); setOpportunity(publishedOpportunities.find((item) => item.projectId === projectId) ?? null)
      if (role === 'university') setRoster(await listMyInstitutionRoster())
      setSelectedMilestone((current) => current ? nextBoard.milestones.find((item) => item.id === current.id) ?? nextBoard.milestones.find((item) => item.status === 'current') ?? nextBoard.milestones[0] : nextBoard.milestones.find((item) => item.status === 'current') ?? nextBoard.milestones[0])
      setNotice('')
    } catch (loadError) { setError(loadError instanceof Error ? loadError.message : 'Unable to load the project workspace.') } finally { setLoading(false) }
  }

  useEffect(() => { const onHashChange = () => setProjectId(projectFromHash()); window.addEventListener('hashchange', onHashChange); void load(); const reconnect = () => { if (document.visibilityState === 'visible') void load() }; window.addEventListener('online', reconnect); document.addEventListener('visibilitychange', reconnect); return () => { window.removeEventListener('hashchange', onHashChange); window.removeEventListener('online', reconnect); document.removeEventListener('visibilitychange', reconnect) } }, [projectId])

  const currentMember = members.find((member) => member.userId === user?.id && member.status === 'active')
  const canManageTeam = role === 'university' && currentMember?.role === 'lead' && board?.closureStatus !== 'closed'
  const canEditRecords = Boolean(currentMember && board?.closureStatus !== 'closed')
  const canSubmitEvidence = role === 'university' && currentMember?.role === 'lead' && board?.closureStatus !== 'closed'
  const currentStage = board?.milestones.find((milestone) => milestone.status === 'current')
  const nextStage = board?.milestones.find((milestone) => milestone.status === 'upcoming')
  const approvedReview = nextStage ? reviewHistory.find((review) => review.targetStage === nextStage.id && review.status === 'approved' && !review.consumedAt) : undefined
  const availableRoster = useMemo(() => roster.filter((member) => member.status === 'active' && !members.some((existing) => existing.userId === member.userId) && (teamRole === 'student' ? member.role === 'student' : ['mentor', 'coordinator'].includes(member.role))), [members, roster, teamRole])
  const records = board ? board[recordKind] : []

  const openProject = (id: string) => { localStorage.setItem('civicx_project_id', id); window.location.hash = `#/projects/${encodeURIComponent(id)}`; setProjectId(id) }
  const backToProjects = () => { localStorage.removeItem('civicx_project_id'); window.location.hash = '#/projects'; setProjectId(''); setBoard(null) }
  const submitEvidence = async (event: FormEvent) => { event.preventDefault(); if (!board || !canSubmitEvidence || !currentStage) return; if (evidenceNote.trim().length < 10) { setError('Describe the evidence in at least 10 characters.'); return } const links = evidenceLinks.split(/\r?\n|,/).map((value) => value.trim()).filter(Boolean); setBusy(true); setError(''); setNotice(''); try { const next = await submitMilestoneEvidence(board.id, currentStage.id, evidenceNote.trim(), board.version, links); setBoard(next); setEvidenceHistory(await listMilestoneEvidence(board.id)); setReviewHistory(await listMilestoneReviews(board.id)); setEvidenceNote(''); setEvidenceLinks(''); setShowEvidenceForm(false); setSelectedMilestone(next.milestones.find((item) => item.status === 'current') ?? next.milestones[0]); setNotice('Evidence submitted for administrator review.') } catch (submitError) { setError(submitError instanceof Error ? submitError.message : 'Unable to submit evidence.') } finally { setBusy(false) } }
  const advance = async () => { if (!board || !canSubmitEvidence || !nextStage || !approvedReview) return; setBusy(true); setError(''); setNotice(''); try { const result = await advanceProjectStage(board.id, nextStage.id, approvedReview.reviewId, board.version); setBoard(result.board); setReviewHistory(await listMilestoneReviews(board.id)); setSelectedMilestone(result.board.milestones.find((item) => item.status === 'current') ?? result.board.milestones[0]); setNotice(`Project advanced to ${nextStage.id}.`) } catch (advanceError) { setError(advanceError instanceof Error ? advanceError.message : 'Unable to advance the project.') } finally { setBusy(false) } }
  const addRecord = async () => { if (!board || !canEditRecords || !recordTitle.trim() || !recordDetail.trim()) { setError('Add a title and detail before saving a record.'); return } setBusy(true); setError(''); setNotice(''); try { const next = await addProjectRecord(board.id, recordKind, { title: recordTitle.trim(), detail: recordDetail.trim(), author: '' }, board.version); setBoard(next); setRecordTitle(''); setRecordDetail(''); setNotice(`${recordLabels[recordKind]} record saved.`) } catch (recordError) { setError(recordError instanceof Error ? recordError.message : 'Unable to save the record.') } finally { setBusy(false) } }
  const addTeamMember = async (event: FormEvent) => { event.preventDefault(); if (!board || !canManageTeam || !teamUserId) { setError('Only the active project lead can add a verified roster member.'); return } setBusy(true); setError(''); setNotice(''); try { await addProjectMember(board.id, { userId: teamUserId, role: teamRole, expectedVersion: board.version }); setTeamUserId(''); setShowTeam(false); await load(); setNotice('Verified team member added.') } catch (memberError) { setError(memberError instanceof Error ? memberError.message : 'Unable to add this team member.') } finally { setBusy(false) } }
  const updateProposal = (field: keyof ProposalInput, value: string) => setProposal((current) => ({ ...current, [field]: value }))
  const submitProposal = async (event: FormEvent) => { event.preventDefault(); if (!board || !currentMember || !['lead', 'mentor'].includes(currentMember.role)) { setError('Only an active project lead or mentor can submit a proposal.'); return } setBusy(true); setError(''); setNotice(''); const input = { ...proposal, ...(proposal.budgetMinor !== undefined && proposal.budgetMinor !== null && String(proposal.budgetMinor) !== '' ? { budgetMinor: Number(proposal.budgetMinor) } : {}), ...(proposal.currency?.trim() ? { currency: proposal.currency.trim().toUpperCase() } : {}) }; try { await submitProjectProposal(board.id, input); setShowProposal(false); setProposal({ approach: '', timeline: '', beneficiaries: '', rootCause: '', workPlan: '', risks: '', resources: '' }); setProposals(await listProjectProposals(board.id)); setNotice('Proposal revision submitted for administrator review.') } catch (proposalError) { setError(proposalError instanceof Error ? proposalError.message : 'Unable to submit the proposal.') } finally { setBusy(false) } }
  const publishOpportunity = async (event: FormEvent) => { event.preventDefault(); if (!board || !currentMember || !['lead', 'mentor'].includes(currentMember.role)) { setError('Only an active project lead or mentor can publish an opportunity.'); return } if (opportunityTitle.trim().length < 3 || opportunitySummary.trim().length < 20 || !opportunityNeeds.length) { setError('Add a title, a clear summary, and at least one support need.'); return } setBusy(true); setError(''); setNotice(''); try { const created = await publishUniversityOpportunity({ projectId: board.id, title: opportunityTitle.trim(), summary: opportunitySummary.trim(), needs: opportunityNeeds }); setOpportunity(created); setShowOpportunity(false); setNotice('Industry opportunity published.') } catch (publishError) { setError(publishError instanceof Error ? publishError.message : 'Unable to publish the opportunity.') } finally { setBusy(false) } }
  const toggleOpportunityNeed = (need: CollaborationType) => setOpportunityNeeds((current) => current.includes(need) ? current.filter((item) => item !== need) : [...current, need])

  if (loading && !projects.length && !board) return <section className="project-board"><p className="board-loading">Loading authorized projects…</p></section>
  if (!projectId) return <section className="project-board"><div className="board-heading"><div><p className="eyebrow"><span /> {role === 'university' ? 'University workspace' : 'Industry workspace'}</p><h1>Authorized projects</h1><p>Open the projects your account is allowed to see. Access comes from active project membership or an accepted collaboration.</p></div><button type="button" onClick={() => void load()} disabled={loading}>↻ Refresh</button></div>{error && <p className="board-error" role="alert">{error}</p>}{projects.length ? <div className="project-list-grid">{projects.map((project) => <button type="button" className="project-summary-card" key={project.id} onClick={() => openProject(project.id)}><span className="project-card-stage">{project.currentStage}</span><h2>{project.title}</h2><p>{project.summary}</p><small>{project.domain} · {project.department} · updated {formatDate(project.updatedAt)}</small><b>Open project →</b></button>)}</div> : <p className="board-empty">No authorized projects are available yet. Accept a university assignment or wait for an accepted collaboration.</p>}</section>
  if (!board) return <section className="project-board"><p className="board-loading">Loading project…</p>{error && <p className="board-error" role="alert">{error}</p>}</section>

  return <section className="project-board"><div className="board-heading"><div><p className="eyebrow"><span /> {role === 'university' ? 'University project board' : 'Industry project view'}</p><h1>{board.title}</h1><p>{board.summary}</p></div><div className="board-heading-actions"><span className="board-version">Version {board.version} · synced {formatDate(board.updatedAt)}</span><button type="button" onClick={backToProjects}>← All projects</button><button type="button" onClick={() => void load()} disabled={loading}>↻ Refresh</button></div></div>{notice && <p className="board-notice" role="status">{notice}</p>}{error && <p className="board-error" role="alert">{error}</p>}
    <div className="board-layout"><div className="milestone-panel"><div className="panel-heading"><div><p className="section-kicker">01 <strong>Milestone timeline</strong></p><h2>Evidence is reviewed before the next stage.</h2></div><span>{canSubmitEvidence ? 'Lead editing enabled' : 'Read only'}</span></div><div className="milestone-list">{board.milestones.map((milestone, index) => <article className={`milestone milestone-${milestone.status} ${selectedMilestone?.id === milestone.id ? 'selected' : ''}`} key={milestone.id} onClick={() => setSelectedMilestone(milestone)}><div className="milestone-marker"><span>{index + 1}</span></div><div className="milestone-content"><div className="milestone-top"><strong>{milestone.title}</strong><span>{milestone.status}</span></div><p>{milestone.description}</p><small>Owner {milestone.owner}</small>{canSubmitEvidence && milestone.status === 'current' && <div className="milestone-actions"><button type="button" disabled={busy} onClick={(event) => { event.stopPropagation(); setShowEvidenceForm(true); setSelectedMilestone(milestone) }}>{evidenceHistory.some((item) => item.targetStage === nextStage?.id && item.status === 'pending') ? 'Update evidence' : 'Submit evidence for review'}</button>{approvedReview && <button type="button" className="milestone-advance-button" disabled={busy} onClick={(event) => { event.stopPropagation(); void advance() }}>Advance to {nextStage?.id}</button>}</div>}</div></article>)}</div></div><aside className="milestone-detail"><p className="section-kicker">02 <strong>Selected milestone</strong></p>{selectedMilestone ? <><h2>{selectedMilestone.title}</h2><p>{selectedMilestone.description}</p><dl><div><dt>Status</dt><dd>{selectedMilestone.status}</dd></div><div><dt>Owner</dt><dd>{selectedMilestone.owner}</dd></div></dl></> : <p>Select a milestone to inspect it.</p>}{showEvidenceForm && canSubmitEvidence && currentStage && <form className="evidence-form" onSubmit={(event) => void submitEvidence(event)}><h3>Submit evidence for {nextStage?.title ?? 'the next milestone'}</h3><label>Evidence note<textarea value={evidenceNote} onChange={(event) => setEvidenceNote(event.target.value)} minLength={10} rows={4} placeholder="Describe the resource, result, or handoff you are submitting." required /></label><label>Evidence links<small>One URL per line or separated by commas.</small><textarea value={evidenceLinks} onChange={(event) => setEvidenceLinks(event.target.value)} rows={2} placeholder="https://…" /></label><div className="evidence-form-actions"><button type="button" onClick={() => setShowEvidenceForm(false)}>Cancel</button><button type="submit" disabled={busy}>{busy ? 'Submitting…' : 'Submit for review'}</button></div></form>}</aside></div>
    <section className="evidence-history-section"><div className="records-heading"><div><p className="section-kicker">03 <strong>Evidence history</strong></p><h2>Every submission and review stays visible.</h2></div><span className="board-version">{evidenceHistory.length} submission{evidenceHistory.length === 1 ? '' : 's'}</span></div>{evidenceHistory.length ? <div className="evidence-history-list">{evidenceHistory.map((item) => { const review = reviewHistory.find((entry) => entry.evidenceId === item.evidenceId); return <article key={item.evidenceId}><div className="evidence-history-head"><div><strong>{item.targetStage} · revision {item.revision}</strong><small>Submitted {formatDate(item.submittedAt)}</small></div><span className={`evidence-status evidence-${item.status}`}>{item.status}</span></div><p>{item.note}</p>{item.links.length > 0 && <div className="evidence-links">{item.links.map((link) => <a href={link} target="_blank" rel="noreferrer" key={link}>{link}</a>)}</div>}{review && <div className="evidence-review"><strong>Administrator {review.status}</strong><span>{review.note}</span>{review.consumedAt && <small>Used to advance the project.</small>}</div>}</article>})}</div> : <p className="board-empty">No milestone evidence has been submitted yet.</p>}</section>
    <section className="project-team-section"><div className="records-heading"><div><p className="section-kicker">04 <strong>Verified project team</strong></p><h2>People with authorized access.</h2></div>{canManageTeam && <button type="button" className="team-manage-button" onClick={() => setShowTeam((current) => !current)}>+ Add roster member</button>}</div><div className="team-member-grid">{members.length ? members.map((member) => <article key={member.id}><span className="member-avatar">{(member.name ?? member.email ?? '?').slice(0, 1).toUpperCase()}</span><div><strong>{member.name ?? member.email ?? 'Project member'}</strong><small>{member.role.replace('_', ' ')}{member.department ? ` · ${member.department}` : ''}</small></div></article>) : <p className="board-empty">No project memberships are available.</p>}</div>{showTeam && canManageTeam && <form className="team-form" onSubmit={(event) => void addTeamMember(event)}><label>Verified roster member<select value={teamUserId} onChange={(event) => setTeamUserId(event.target.value)} required><option value="">Choose a member</option>{availableRoster.map((member) => <option key={member.userId} value={member.userId}>{member.name} · {member.role}{member.department ? ` · ${member.department}` : ''}</option>)}</select></label><label>Project role<select value={teamRole} onChange={(event) => setTeamRole(event.target.value as 'mentor' | 'student')}><option value="student">Student</option><option value="mentor">Mentor</option></select></label><button type="submit" disabled={busy}>{busy ? 'Adding…' : 'Add to project'}</button></form>}{role === 'university' && !canManageTeam && currentMember && <p className="team-permission-note">Only the active project lead can manage the verified team.</p>}</section>
    <section className="proposal-section"><div className="records-heading"><div><p className="section-kicker">05 <strong>Proposal revisions</strong></p><h2>Keep the plan reviewable.</h2></div>{currentMember && ['lead', 'mentor'].includes(currentMember.role) && board.closureStatus !== 'closed' && <button type="button" className="team-manage-button" onClick={() => setShowProposal((current) => !current)}>+ New revision</button>}</div>{proposals.length ? <div className="proposal-list">{proposals.map((item) => <article key={item.id}><div className="proposal-list-head"><div><strong>Revision {item.revision}</strong><small>{item.status} · submitted {formatDate(item.createdAt)}</small></div><span className={`proposal-status proposal-${item.status}`}>{item.status}</span></div><p>{item.approach}</p>{item.reviews?.map((review) => <div className="proposal-review" key={review.reviewId}><strong>{review.status}</strong><span>{review.note}</span></div>)}</article>)}</div> : <p className="board-empty">No proposal revision has been submitted yet.</p>}{showProposal && <form className="proposal-form" onSubmit={(event) => void submitProposal(event)}><h3>Submit a proposal revision</h3><div className="proposal-form-grid"><label>Approach<textarea value={proposal.approach} onChange={(event) => updateProposal('approach', event.target.value)} minLength={20} rows={3} required /></label><label>Timeline<textarea value={proposal.timeline} onChange={(event) => updateProposal('timeline', event.target.value)} rows={3} required /></label><label>Beneficiaries<textarea value={proposal.beneficiaries} onChange={(event) => updateProposal('beneficiaries', event.target.value)} minLength={10} rows={3} required /></label><label>Root cause<textarea value={proposal.rootCause} onChange={(event) => updateProposal('rootCause', event.target.value)} minLength={10} rows={3} required /></label><label>Work plan<textarea value={proposal.workPlan} onChange={(event) => updateProposal('workPlan', event.target.value)} minLength={20} rows={3} required /></label><label>Risks<textarea value={proposal.risks} onChange={(event) => updateProposal('risks', event.target.value)} minLength={10} rows={3} required /></label><label>Resources<textarea value={proposal.resources} onChange={(event) => updateProposal('resources', event.target.value)} minLength={10} rows={3} required /></label><label>Budget (minor units)<input type="number" min="0" value={proposal.budgetMinor ?? ''} onChange={(event) => setProposal((current) => ({ ...current, budgetMinor: event.target.value === '' ? undefined : Number(event.target.value) }))} /></label><label>Currency<input maxLength={3} value={proposal.currency ?? ''} onChange={(event) => updateProposal('currency', event.target.value)} placeholder="INR" /></label></div><button className="proposal-save" type="submit" disabled={busy}>{busy ? 'Submitting…' : 'Submit for administrator review'} <span>→</span></button></form>}</section>
    {role === 'university' && <section className="opportunity-section"><div className="records-heading"><div><p className="section-kicker">06 <strong>Industry opportunity</strong></p><h2>Turn an approved proposal into a structured partner request.</h2></div>{!opportunity && currentMember && ['lead', 'mentor'].includes(currentMember.role) && <button type="button" className="team-manage-button" onClick={() => setShowOpportunity((current) => !current)}>+ Publish opportunity</button>}</div>{opportunity ? <div className="published-opportunity"><div><span className="opportunity-status">{opportunity.status}</span><h3>{opportunity.title}</h3><p>{opportunity.summary}</p></div><div className="opportunity-needs"><strong>Requested support</strong><div>{opportunity.needs.map((need) => <span key={need}>{supportLabels[need]}</span>)}</div></div><small>Published {formatDate(opportunity.createdAt)} · visible to approved industry institutions</small></div> : proposals.some((item) => item.status === 'approved') ? showOpportunity ? <form className="opportunity-form" onSubmit={(event) => void publishOpportunity(event)}><h3>Publish a partner opportunity</h3><p>Describe the approved project and choose the support types that an industry partner can offer.</p><label>Title<input value={opportunityTitle} onChange={(event) => setOpportunityTitle(event.target.value)} minLength={3} required /></label><label>Summary<textarea value={opportunitySummary} onChange={(event) => setOpportunitySummary(event.target.value)} minLength={20} rows={4} required /></label><fieldset><legend>Support needed</legend>{(['mentorship', 'funding', 'prototyping', 'deployment', 'technology_transfer'] as CollaborationType[]).map((need) => <label key={need}><input type="checkbox" checked={opportunityNeeds.includes(need)} onChange={() => toggleOpportunityNeed(need)} /> {supportLabels[need]}</label>)}</fieldset><button className="proposal-save" type="submit" disabled={busy}>{busy ? 'Publishing…' : 'Publish to industry'} <span>→</span></button></form> : <p className="opportunity-locked">An approved proposal is ready. Publish an opportunity when you are ready to describe the support this project needs.</p> : <p className="opportunity-locked">An administrator must approve a proposal before this project can be published to industry.</p>}</section>}
    <div className="records-section"><div className="records-heading"><div><p className="section-kicker">07 <strong>Project evidence</strong></p><h2>Deliverables, disclosures, and tests.</h2></div><div className="record-tabs">{(Object.keys(recordLabels) as RecordKind[]).map((kind) => <button type="button" className={recordKind === kind ? 'active' : ''} key={kind} onClick={() => setRecordKind(kind)}>{recordLabels[kind]}</button>)}</div></div><div className="record-layout"><div className="record-list">{records.length ? records.map((record: ProjectRecord) => <article key={record.id}><div><strong>{record.title}</strong><small>{record.author} · {formatDate(record.createdAt)}</small></div><p>{record.detail}</p></article>) : <p className="empty-records">No {recordLabels[recordKind].toLowerCase()} recorded.</p>}</div>{canEditRecords && <div className="record-form"><h3>Add {recordLabels[recordKind].toLowerCase().slice(0, -1)}</h3><label>Title<input value={recordTitle} onChange={(event) => setRecordTitle(event.target.value)} placeholder="Record title" /></label><label>Detail<textarea value={recordDetail} onChange={(event) => setRecordDetail(event.target.value)} placeholder="What should authorized project users know?" rows={4} /></label><button type="button" disabled={busy} onClick={() => void addRecord()}>{busy ? 'Saving…' : 'Save record'} <span>→</span></button></div>}</div></div>
    {board.outcome && <section className="project-outcome-section"><div className="records-heading"><div><p className="section-kicker">08 <strong>Validated outcome</strong></p><h2>The measured result is now part of the project record.</h2></div><span className="outcome-closed-label">{board.closureStatus === 'closed' ? 'Project closed' : 'Validated'}</span></div><div className="project-outcome-grid"><article><small>Baseline</small><strong>{board.outcome.baseline}</strong></article><article><small>Target</small><strong>{board.outcome.target ?? '—'}</strong></article><article><small>Measured result</small><strong>{board.outcome.result} {board.outcome.unit}</strong></article><article><small>Beneficiaries</small><strong>{board.outcome.beneficiaries ?? '—'}</strong></article></div><p className="project-outcome-note">{board.outcome.validationNote ?? 'The administrator validated this result.'} {board.outcome.validatedAt ? `Validated ${formatDate(board.outcome.validatedAt)}.` : ''}</p></section>}
  </section>
}
